On:
 push:
  branches:
 - main



 jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
     uses: actions/checkout@v1

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secrets-access-key: ${{ secrets.AWS_SEcret_ACCESS_key }}
         aws-region: ap-northeast-1a

         - name: Deploy start site to S3 bucket
           run: aws s3 sync . s3://varun-portfolio --delete
